version: '3'

services:
###> doctrine/doctrine-bundle ###
  furnics-database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  furnics-mailer:
    image: axllent/mailpit
    container_name: furnics-mailer
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
